### ISSUE TITLE
[BUG] Icons Overlap on Floating Button

### ISSUE THREAD

**Issue by astro-ray** [suvam0451/dhaaga#103] opened 2024-08-02 02:49 UTC
The floating button in the timeline, the filter icon overlaps on the `Switch Timeline` icon.

![Screenshot_20240802_081315_Dhaaga (Lite).jpg](https://github.com/user-attachments/assets/414a5348-436d-44d4-9a71-756910241960)

More Info:
Installed from: Github
Instance Software: Misskey

**Comment by suvam0451** [comment] 2024-08-02 04:12
Thanks.

Yeah, this becomes an issue in multiple places.

The problem is that material design recommends using opacity to present emphasis. But, because of using opacity, some overlapping element visually bleed through, haha.

Will fix in next release 👌

<img width="320" alt="Screenshot 2024-08-02 at 9 34 35 AM" src="https://github.com/user-attachments/assets/7020ca92-bedc-490a-bf1d-d1204fcca37f">


<img width="480" alt="Screenshot 2024-08-02 at 9 39 15 AM" src="https://github.com/user-attachments/assets/417ff15f-2a20-48c1-9ca3-31ac7efbf968">

**Comment by suvam0451** [comment] 2024-08-03 12:54
Fixed in v0.6.0

**Closed by suvam0451** 2024-08-03 12:54 UTC
Labels: bug
